---
kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test

- name: notify
  image: plugins/slack
  settings:
    webhook: https://hooks.slack.com/services/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
  when:
    status: [ success, failure ]